name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [21.x]  
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install and Build Backend
      run: |
        cd backend
        npm install
        npm run build
        pm2 stop 0
        pm2 start 0
    - name: Install and Build Client
      run: |
        cd client
        npm install
        npm run build
        rm -rf /var/www/client/*
        cp -r dist/* /var/www/client
